site_name: rsprta/mariadb-backup
site_url: "https://radek-sprta.gitlab.io/docker-mariadb-backup"
site_author: Radek Sprta
theme: cinder
nav:
  - Home: index.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md
repo_url: https://gitlab.com/radek-sprta/docker-mariadb-backup
